// Cross-platform "start the gateway at login". Same philosophy as power.mjs:
// shell out to per-user OS mechanisms, never require elevation, and make
// disable remove every trace so the machine is back to its original state.
//
//   win32  – HKCU\...\Run registry value pointing at a hidden-window .vbs
//            wrapper (registering node directly would open a console at login).
//   darwin – LaunchAgent plist in ~/Library/LaunchAgents with RunAtLoad. We
//            only write the file (launchd picks it up at next login) and never
//            launchctl-start it now, so enabling can't spawn a duplicate of
//            the already-running server.
//   linux  – systemd user unit when systemctl exists, XDG autostart .desktop
//            entry otherwise (covers non-systemd distros and WSL desktops).
//
// Enabled-at-login instances that lose the port race exit cleanly (the server
// treats EADDRINUSE as "already running"), so autostart + a manual launch never
// leaves a crash-looping ghost.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { config, ROOT } from "./config.mjs";

const platform = process.platform; // "win32" | "darwin" | "linux"
const NODE = process.execPath; // exact node binary, immune to PATH differences at login
const SERVER = path.join(ROOT, "server.mjs");
const LOG = path.join(config.runtimeDir, "autostart.log");

const run = (cmd, args) => new Promise((resolve) => {
  execFile(cmd, args, { timeout: 10000, windowsHide: true }, (err) =>
    resolve({ ok: !err, missing: !!err && err.code === "ENOENT" }));
});

// --- Windows: HKCU Run key + hidden VBS wrapper ------------------------------

const WIN_KEY = "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run";
const WIN_VALUE = "Wakili";
const VBS = path.join(config.runtimeDir, "autostart.vbs");

// WScript.Shell.Run with window style 0 starts the server fully hidden; going
// through cmd routes stdout/stderr into a log. Inside a VBScript string every
// literal quote is doubled ("" = one ").
function writeVbs() {
  fs.writeFileSync(VBS, [
    "' Auto-generated by Wakili - starts the gateway hidden at login.",
    'Set sh = CreateObject("WScript.Shell")',
    `sh.CurrentDirectory = "${ROOT}"`,
    `sh.Run "cmd /c """"${NODE}"" ""${SERVER}"" >> ""${LOG}"" 2>&1""", 0, False`,
    "",
  ].join("\r\n"));
}

// --- macOS: LaunchAgent plist -------------------------------------------------

const PLIST = path.join(os.homedir(), "Library", "LaunchAgents", "com.wakili.gateway.plist");
const xml = (s) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

function plistBody() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>com.wakili.gateway</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xml(NODE)}</string>
    <string>${xml(SERVER)}</string>
  </array>
  <key>WorkingDirectory</key><string>${xml(ROOT)}</string>
  <key>RunAtLoad</key><true/>
  <key>StandardOutPath</key><string>${xml(LOG)}</string>
  <key>StandardErrorPath</key><string>${xml(LOG)}</string>
</dict>
</plist>
`;
}

// --- Linux: systemd user unit, XDG autostart fallback -------------------------

const UNIT_NAME = "wakili.service";
const UNIT = path.join(os.homedir(), ".config", "systemd", "user", UNIT_NAME);
const DESKTOP = path.join(os.homedir(), ".config", "autostart", "wakili.desktop");

function unitBody() {
  return `[Unit]
Description=Wakili phone gateway

[Service]
ExecStart="${NODE}" "${SERVER}"
WorkingDirectory=${ROOT}
Restart=on-failure

[Install]
WantedBy=default.target
`;
}

function desktopBody() {
  return `[Desktop Entry]
Type=Application
Name=Wakili
Comment=Phone gateway for local coding agents
Exec="${NODE}" "${SERVER}"
Path=${ROOT}
X-GNOME-Autostart-enabled=true
`;
}

// --- Public API ----------------------------------------------------------------

export async function autostartStatus() {
  if (platform === "win32") {
    const q = await run("reg", ["query", WIN_KEY, "/v", WIN_VALUE]);
    return { supported: true, on: q.ok, method: "registry" };
  }
  if (platform === "darwin") {
    return { supported: true, on: fs.existsSync(PLIST), method: "launchd" };
  }
  if (platform === "linux") {
    if (fs.existsSync(UNIT)) {
      const q = await run("systemctl", ["--user", "is-enabled", UNIT_NAME]);
      return { supported: true, on: q.ok, method: "systemd" };
    }
    return { supported: true, on: fs.existsSync(DESKTOP), method: fs.existsSync(DESKTOP) ? "desktop" : "systemd" };
  }
  return { supported: false, on: false, method: "" };
}

export async function setAutostart(on) {
  try {
    if (platform === "win32") {
      if (on) {
        writeVbs();
        const r = await run("reg", ["add", WIN_KEY, "/v", WIN_VALUE, "/t", "REG_SZ", "/d", `wscript.exe "${VBS}"`, "/f"]);
        if (!r.ok) return { ...(await autostartStatus()), error: "Couldn't write the registry Run entry." };
      } else {
        await run("reg", ["delete", WIN_KEY, "/v", WIN_VALUE, "/f"]);
        try { fs.unlinkSync(VBS); } catch { /* never written or already gone */ }
      }
    } else if (platform === "darwin") {
      if (on) {
        fs.mkdirSync(path.dirname(PLIST), { recursive: true });
        fs.writeFileSync(PLIST, plistBody());
      } else {
        try { fs.unlinkSync(PLIST); } catch { /* already gone */ }
      }
    } else if (platform === "linux") {
      if (on) {
        // Prefer systemd; if systemctl isn't there, fall back to XDG autostart.
        fs.mkdirSync(path.dirname(UNIT), { recursive: true });
        fs.writeFileSync(UNIT, unitBody());
        await run("systemctl", ["--user", "daemon-reload"]);
        const en = await run("systemctl", ["--user", "enable", UNIT_NAME]);
        if (!en.ok) {
          try { fs.unlinkSync(UNIT); } catch { /* just written; ignore */ }
          fs.mkdirSync(path.dirname(DESKTOP), { recursive: true });
          fs.writeFileSync(DESKTOP, desktopBody());
        }
      } else {
        if (fs.existsSync(UNIT)) {
          await run("systemctl", ["--user", "disable", UNIT_NAME]);
          try { fs.unlinkSync(UNIT); } catch { /* already gone */ }
          await run("systemctl", ["--user", "daemon-reload"]);
        }
        try { fs.unlinkSync(DESKTOP); } catch { /* already gone */ }
      }
    }
  } catch (e) {
    return { ...(await autostartStatus()), error: String((e && e.message) || e) };
  }
  return autostartStatus();
}

// --- First-run enrollment -------------------------------------------------------
// Start-at-login is ON by default: the very first launch registers autostart and
// drops a marker file recording that the automatic enable already happened. From
// then on the user's choice (the app's Settings toggle) is final — the server
// never re-enables it behind their back. Skipped for ephemeral installs (the npx
// cache): registering a path into a temp folder would break at the next login.
const ENROLL_MARKER = path.join(config.runtimeDir, "autostart-enrolled");

export async function enrollAutostartOnce() {
  try {
    if (fs.existsSync(ENROLL_MARKER)) return;
    if (/[\\/]_npx[\\/]/.test(ROOT)) return;
    const cur = await autostartStatus();
    if (!cur.supported) return;
    if (!cur.on) {
      const r = await setAutostart(true);
      if (r.error) return; // couldn't register — no marker written, so we retry next launch
      console.log("  Start at login: enabled by default — turn it off anytime in the app's Settings.");
    }
    fs.writeFileSync(ENROLL_MARKER,
      "Records that Wakili's one-time default enabling of start-at-login already ran.\n" +
      "While this file exists the server never touches the setting again - the app's toggle rules.\n");
  } catch { /* enrollment must never block startup */ }
}

// Self-heal: when start-at-login is enabled, re-register it pointing at THIS
// install every startup. Registration embeds absolute node/server paths, so a
// moved repo, a renamed folder, or a node upgrade leaves a launcher pointing at
// nothing — on Windows that's a WScript error box at every login and no gateway.
// Rewriting is idempotent and only ever flips paths to the copy actually running.
export async function refreshAutostart() {
  try {
    if (/[\\/]_npx[\\/]/.test(ROOT)) return; // ephemeral install — never register its paths
    const cur = await autostartStatus();
    if (cur.supported && cur.on) await setAutostart(true);
  } catch { /* best effort — never block startup */ }
}

// --- Legacy identity migration ------------------------------------------------
// Before the rename to Wakili, autostart registered under "Remote Agent": the
// Windows Run value "RemoteAgent" (its .vbs launcher lived inside <repo>/data),
// macOS com.remote-agent.gateway, Linux remote-agent.service / .desktop. Those
// entries are now stale — the launcher path moved with the store to ~/.wakili.
// reconcileAutostart() carries an enabled autostart over to the new identity and
// removes the old registration. Idempotent: a no-op once the legacy entry is gone.
const LEGACY_WIN_VALUE = "RemoteAgent";
const LEGACY_PLIST = path.join(os.homedir(), "Library", "LaunchAgents", "com.remote-agent.gateway.plist");
const LEGACY_UNIT_NAME = "remote-agent.service";
const LEGACY_UNIT = path.join(os.homedir(), ".config", "systemd", "user", LEGACY_UNIT_NAME);
const LEGACY_DESKTOP = path.join(os.homedir(), ".config", "autostart", "remote-agent.desktop");

async function legacyState() {
  if (platform === "win32") {
    const q = await run("reg", ["query", WIN_KEY, "/v", LEGACY_WIN_VALUE]);
    return { present: q.ok, on: q.ok }; // a Run value is either there (on) or not
  }
  if (platform === "darwin") {
    const p = fs.existsSync(LEGACY_PLIST);
    return { present: p, on: p };
  }
  if (platform === "linux") {
    if (fs.existsSync(LEGACY_UNIT)) {
      const q = await run("systemctl", ["--user", "is-enabled", LEGACY_UNIT_NAME]);
      return { present: true, on: q.ok };
    }
    const d = fs.existsSync(LEGACY_DESKTOP);
    return { present: d, on: d };
  }
  return { present: false, on: false };
}

async function removeLegacy() {
  if (platform === "win32") {
    await run("reg", ["delete", WIN_KEY, "/v", LEGACY_WIN_VALUE, "/f"]);
  } else if (platform === "darwin") {
    try { fs.unlinkSync(LEGACY_PLIST); } catch { /* already gone */ }
  } else if (platform === "linux") {
    if (fs.existsSync(LEGACY_UNIT)) {
      await run("systemctl", ["--user", "disable", LEGACY_UNIT_NAME]);
      try { fs.unlinkSync(LEGACY_UNIT); } catch { /* already gone */ }
      await run("systemctl", ["--user", "daemon-reload"]);
    }
    try { fs.unlinkSync(LEGACY_DESKTOP); } catch { /* already gone */ }
  }
}

// Returns true when the legacy store folder is safe to delete — i.e. any enabled
// autostart is now running from the new location, so nothing left points into the
// folder about to be removed. Returns false only if establishing the new entry
// failed (then the caller keeps the old folder so login startup isn't broken).
export async function reconcileAutostart() {
  try {
    const legacy = await legacyState();
    if (!legacy.present) return true; // nothing old to migrate
    if (legacy.on) {
      const cur = await autostartStatus();
      if (!cur.on) {
        const r = await setAutostart(true); // register under the new identity/location first
        if (r && r.error) return false;      // couldn't — leave the legacy entry working
      }
    }
    await removeLegacy();
    return true;
  } catch { return false; }
}
